//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebraEventManagementDesktop.MemberServiceRefDesktop {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ticket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TicketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNameField;
        
        private decimal PriceField;
        
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TicketId {
            get {
                return this.TicketIdField;
            }
            set {
                if ((this.TicketIdField.Equals(value) != true)) {
                    this.TicketIdField = value;
                    this.RaisePropertyChanged("TicketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicketName {
            get {
                return this.TicketNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNameField, value) != true)) {
                    this.TicketNameField = value;
                    this.RaisePropertyChanged("TicketName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EventDate {
            get {
                return this.EventDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDateField, value) != true)) {
                    this.EventDateField = value;
                    this.RaisePropertyChanged("EventDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTimeField, value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberServiceRefDesktop.MemberServicesSoap")]
    public interface MemberServicesSoap {
        
        // CODEGEN: Generating message contract since element name memberName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterMember", ReplyAction="*")]
        DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponse RegisterMember(DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterMember", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponse> RegisterMemberAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest request);
        
        // CODEGEN: Generating message contract since element name GetAvailableTicketsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableTickets", ReplyAction="*")]
        DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponse GetAvailableTickets(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponse> GetAvailableTicketsAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest request);
        
        // CODEGEN: Generating message contract since element name memberEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookTicket", ReplyAction="*")]
        DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponse BookTicket(DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponse> BookTicketAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest request);
        
        // CODEGEN: Generating message contract since element name GetAvailableEventsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableEvents", ReplyAction="*")]
        DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponse GetAvailableEvents(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponse> GetAvailableEventsAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginMember", ReplyAction="*")]
        DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponse LoginMember(DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginMember", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponse> LoginMemberAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterMember", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequestBody Body;
        
        public RegisterMemberRequest() {
        }
        
        public RegisterMemberRequest(DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string memberName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public RegisterMemberRequestBody() {
        }
        
        public RegisterMemberRequestBody(string memberName, string email, string password) {
            this.memberName = memberName;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponseBody Body;
        
        public RegisterMemberResponse() {
        }
        
        public RegisterMemberResponse(DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterMemberResult;
        
        public RegisterMemberResponseBody() {
        }
        
        public RegisterMemberResponseBody(bool RegisterMemberResult) {
            this.RegisterMemberResult = RegisterMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableTickets", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequestBody Body;
        
        public GetAvailableTicketsRequest() {
        }
        
        public GetAvailableTicketsRequest(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAvailableTicketsRequestBody {
        
        public GetAvailableTicketsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponseBody Body;
        
        public GetAvailableTicketsResponse() {
        }
        
        public GetAvailableTicketsResponse(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableTicketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.Ticket[] GetAvailableTicketsResult;
        
        public GetAvailableTicketsResponseBody() {
        }
        
        public GetAvailableTicketsResponseBody(DebraEventManagementDesktop.MemberServiceRefDesktop.Ticket[] GetAvailableTicketsResult) {
            this.GetAvailableTicketsResult = GetAvailableTicketsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookTicket", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequestBody Body;
        
        public BookTicketRequest() {
        }
        
        public BookTicketRequest(DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ticketId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string memberEmail;
        
        public BookTicketRequestBody() {
        }
        
        public BookTicketRequestBody(int ticketId, string memberEmail) {
            this.ticketId = ticketId;
            this.memberEmail = memberEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookTicketResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponseBody Body;
        
        public BookTicketResponse() {
        }
        
        public BookTicketResponse(DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool BookTicketResult;
        
        public BookTicketResponseBody() {
        }
        
        public BookTicketResponseBody(bool BookTicketResult) {
            this.BookTicketResult = BookTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableEvents", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequestBody Body;
        
        public GetAvailableEventsRequest() {
        }
        
        public GetAvailableEventsRequest(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAvailableEventsRequestBody {
        
        public GetAvailableEventsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableEventsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponseBody Body;
        
        public GetAvailableEventsResponse() {
        }
        
        public GetAvailableEventsResponse(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.EventData[] GetAvailableEventsResult;
        
        public GetAvailableEventsResponseBody() {
        }
        
        public GetAvailableEventsResponseBody(DebraEventManagementDesktop.MemberServiceRefDesktop.EventData[] GetAvailableEventsResult) {
            this.GetAvailableEventsResult = GetAvailableEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginMember", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequestBody Body;
        
        public LoginMemberRequest() {
        }
        
        public LoginMemberRequest(DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginMemberRequestBody() {
        }
        
        public LoginMemberRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponseBody Body;
        
        public LoginMemberResponse() {
        }
        
        public LoginMemberResponse(DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginMemberResult;
        
        public LoginMemberResponseBody() {
        }
        
        public LoginMemberResponseBody(bool LoginMemberResult) {
            this.LoginMemberResult = LoginMemberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MemberServicesSoapChannel : DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberServicesSoapClient : System.ServiceModel.ClientBase<DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap>, DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap {
        
        public MemberServicesSoapClient() {
        }
        
        public MemberServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponse DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.RegisterMember(DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest request) {
            return base.Channel.RegisterMember(request);
        }
        
        public bool RegisterMember(string memberName, string email, string password) {
            DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequestBody();
            inValue.Body.memberName = memberName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponse retVal = ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).RegisterMember(inValue);
            return retVal.Body.RegisterMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponse> DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.RegisterMemberAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest request) {
            return base.Channel.RegisterMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberResponse> RegisterMemberAsync(string memberName, string email, string password) {
            DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.RegisterMemberRequestBody();
            inValue.Body.memberName = memberName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).RegisterMemberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponse DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.GetAvailableTickets(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest request) {
            return base.Channel.GetAvailableTickets(request);
        }
        
        public DebraEventManagementDesktop.MemberServiceRefDesktop.Ticket[] GetAvailableTickets() {
            DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequestBody();
            DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponse retVal = ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).GetAvailableTickets(inValue);
            return retVal.Body.GetAvailableTicketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponse> DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.GetAvailableTicketsAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest request) {
            return base.Channel.GetAvailableTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsResponse> GetAvailableTicketsAsync() {
            DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableTicketsRequestBody();
            return ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).GetAvailableTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponse DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.BookTicket(DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest request) {
            return base.Channel.BookTicket(request);
        }
        
        public bool BookTicket(int ticketId, string memberEmail) {
            DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequestBody();
            inValue.Body.ticketId = ticketId;
            inValue.Body.memberEmail = memberEmail;
            DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponse retVal = ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).BookTicket(inValue);
            return retVal.Body.BookTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponse> DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.BookTicketAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest request) {
            return base.Channel.BookTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketResponse> BookTicketAsync(int ticketId, string memberEmail) {
            DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.BookTicketRequestBody();
            inValue.Body.ticketId = ticketId;
            inValue.Body.memberEmail = memberEmail;
            return ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).BookTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponse DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.GetAvailableEvents(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest request) {
            return base.Channel.GetAvailableEvents(request);
        }
        
        public DebraEventManagementDesktop.MemberServiceRefDesktop.EventData[] GetAvailableEvents() {
            DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequestBody();
            DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponse retVal = ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).GetAvailableEvents(inValue);
            return retVal.Body.GetAvailableEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponse> DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.GetAvailableEventsAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest request) {
            return base.Channel.GetAvailableEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsResponse> GetAvailableEventsAsync() {
            DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.GetAvailableEventsRequestBody();
            return ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).GetAvailableEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponse DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.LoginMember(DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest request) {
            return base.Channel.LoginMember(request);
        }
        
        public bool LoginMember(string email, string password) {
            DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponse retVal = ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).LoginMember(inValue);
            return retVal.Body.LoginMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponse> DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap.LoginMemberAsync(DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest request) {
            return base.Channel.LoginMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberResponse> LoginMemberAsync(string email, string password) {
            DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest inValue = new DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequest();
            inValue.Body = new DebraEventManagementDesktop.MemberServiceRefDesktop.LoginMemberRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((DebraEventManagementDesktop.MemberServiceRefDesktop.MemberServicesSoap)(this)).LoginMemberAsync(inValue);
        }
    }
}
