//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebraEventManagement.PartnerServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventSales", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EventSales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        private int TicketsSoldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TicketsSold {
            get {
                return this.TicketsSoldField;
            }
            set {
                if ((this.TicketsSoldField.Equals(value) != true)) {
                    this.TicketsSoldField = value;
                    this.RaisePropertyChanged("TicketsSold");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartnerServiceRef.PartnerServicesSoap")]
    public interface PartnerServicesSoap {
        
        // CODEGEN: Generating message contract since element name partnerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.RegisterPartnerResponse RegisterPartner(DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.RegisterPartnerResponse> RegisterPartnerAsync(DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginPartner", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.LoginPartnerResponse LoginPartner(DebraEventManagement.PartnerServiceRef.LoginPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.LoginPartnerResponse> LoginPartnerAsync(DebraEventManagement.PartnerServiceRef.LoginPartnerRequest request);
        
        // CODEGEN: Generating message contract since element name partnerEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEvent", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.CreateEventResponse CreateEvent(DebraEventManagement.PartnerServiceRef.CreateEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.CreateEventResponse> CreateEventAsync(DebraEventManagement.PartnerServiceRef.CreateEventRequest request);
        
        // CODEGEN: Generating message contract since element name ticketName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTicketDetails", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponse SetTicketDetails(DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTicketDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponse> SetTicketDetailsAsync(DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name partnerEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatePartnerEarnings", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponse CalculatePartnerEarnings(DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatePartnerEarnings", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponse> CalculatePartnerEarningsAsync(DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventsByPartnerIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsByPartnerId", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponse GetEventsByPartnerId(DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsByPartnerId", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponse> GetEventsByPartnerIdAsync(DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetPartnerTicketSalesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerTicketSales", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponse GetPartnerTicketSales(DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerTicketSales", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponse> GetPartnerTicketSalesAsync(DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerIdByEmail", ReplyAction="*")]
        DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponse GetPartnerIdByEmail(DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerIdByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponse> GetPartnerIdByEmailAsync(DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartner", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.RegisterPartnerRequestBody Body;
        
        public RegisterPartnerRequest() {
        }
        
        public RegisterPartnerRequest(DebraEventManagement.PartnerServiceRef.RegisterPartnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public RegisterPartnerRequestBody() {
        }
        
        public RegisterPartnerRequestBody(string partnerName, string email, string password) {
            this.partnerName = partnerName;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.RegisterPartnerResponseBody Body;
        
        public RegisterPartnerResponse() {
        }
        
        public RegisterPartnerResponse(DebraEventManagement.PartnerServiceRef.RegisterPartnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterPartnerResult;
        
        public RegisterPartnerResponseBody() {
        }
        
        public RegisterPartnerResponseBody(bool RegisterPartnerResult) {
            this.RegisterPartnerResult = RegisterPartnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginPartnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginPartner", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.LoginPartnerRequestBody Body;
        
        public LoginPartnerRequest() {
        }
        
        public LoginPartnerRequest(DebraEventManagement.PartnerServiceRef.LoginPartnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginPartnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginPartnerRequestBody() {
        }
        
        public LoginPartnerRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginPartnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginPartnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.LoginPartnerResponseBody Body;
        
        public LoginPartnerResponse() {
        }
        
        public LoginPartnerResponse(DebraEventManagement.PartnerServiceRef.LoginPartnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginPartnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginPartnerResult;
        
        public LoginPartnerResponseBody() {
        }
        
        public LoginPartnerResponseBody(bool LoginPartnerResult) {
            this.LoginPartnerResult = LoginPartnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEvent", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.CreateEventRequestBody Body;
        
        public CreateEventRequest() {
        }
        
        public CreateEventRequest(DebraEventManagement.PartnerServiceRef.CreateEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string eventName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eventDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string eventDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eventTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string link;
        
        public CreateEventRequestBody() {
        }
        
        public CreateEventRequestBody(string partnerEmail, string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            this.partnerEmail = partnerEmail;
            this.eventName = eventName;
            this.eventDescription = eventDescription;
            this.eventDate = eventDate;
            this.eventTime = eventTime;
            this.location = location;
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEventResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.CreateEventResponseBody Body;
        
        public CreateEventResponse() {
        }
        
        public CreateEventResponse(DebraEventManagement.PartnerServiceRef.CreateEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEventResult;
        
        public CreateEventResponseBody() {
        }
        
        public CreateEventResponseBody(bool CreateEventResult) {
            this.CreateEventResult = CreateEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTicketDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTicketDetails", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequestBody Body;
        
        public SetTicketDetailsRequest() {
        }
        
        public SetTicketDetailsRequest(DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetTicketDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int eventId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ticketName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        public SetTicketDetailsRequestBody() {
        }
        
        public SetTicketDetailsRequestBody(int eventId, string ticketName, decimal price, int quantity) {
            this.eventId = eventId;
            this.ticketName = ticketName;
            this.price = price;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTicketDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTicketDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponseBody Body;
        
        public SetTicketDetailsResponse() {
        }
        
        public SetTicketDetailsResponse(DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetTicketDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetTicketDetailsResult;
        
        public SetTicketDetailsResponseBody() {
        }
        
        public SetTicketDetailsResponseBody(bool SetTicketDetailsResult) {
            this.SetTicketDetailsResult = SetTicketDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePartnerEarningsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePartnerEarnings", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequestBody Body;
        
        public CalculatePartnerEarningsRequest() {
        }
        
        public CalculatePartnerEarningsRequest(DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculatePartnerEarningsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerEmail;
        
        public CalculatePartnerEarningsRequestBody() {
        }
        
        public CalculatePartnerEarningsRequestBody(string partnerEmail) {
            this.partnerEmail = partnerEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePartnerEarningsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePartnerEarningsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponseBody Body;
        
        public CalculatePartnerEarningsResponse() {
        }
        
        public CalculatePartnerEarningsResponse(DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculatePartnerEarningsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal CalculatePartnerEarningsResult;
        
        public CalculatePartnerEarningsResponseBody() {
        }
        
        public CalculatePartnerEarningsResponseBody(decimal CalculatePartnerEarningsResult) {
            this.CalculatePartnerEarningsResult = CalculatePartnerEarningsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsByPartnerIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsByPartnerId", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequestBody Body;
        
        public GetEventsByPartnerIdRequest() {
        }
        
        public GetEventsByPartnerIdRequest(DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventsByPartnerIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int partnerId;
        
        public GetEventsByPartnerIdRequestBody() {
        }
        
        public GetEventsByPartnerIdRequestBody(int partnerId) {
            this.partnerId = partnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsByPartnerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsByPartnerIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponseBody Body;
        
        public GetEventsByPartnerIdResponse() {
        }
        
        public GetEventsByPartnerIdResponse(DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventsByPartnerIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagement.PartnerServiceRef.Event[] GetEventsByPartnerIdResult;
        
        public GetEventsByPartnerIdResponseBody() {
        }
        
        public GetEventsByPartnerIdResponseBody(DebraEventManagement.PartnerServiceRef.Event[] GetEventsByPartnerIdResult) {
            this.GetEventsByPartnerIdResult = GetEventsByPartnerIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerTicketSalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerTicketSales", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequestBody Body;
        
        public GetPartnerTicketSalesRequest() {
        }
        
        public GetPartnerTicketSalesRequest(DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerTicketSalesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int partnerId;
        
        public GetPartnerTicketSalesRequestBody() {
        }
        
        public GetPartnerTicketSalesRequestBody(int partnerId) {
            this.partnerId = partnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerTicketSalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerTicketSalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponseBody Body;
        
        public GetPartnerTicketSalesResponse() {
        }
        
        public GetPartnerTicketSalesResponse(DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerTicketSalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagement.PartnerServiceRef.EventSales[] GetPartnerTicketSalesResult;
        
        public GetPartnerTicketSalesResponseBody() {
        }
        
        public GetPartnerTicketSalesResponseBody(DebraEventManagement.PartnerServiceRef.EventSales[] GetPartnerTicketSalesResult) {
            this.GetPartnerTicketSalesResult = GetPartnerTicketSalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerIdByEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerIdByEmail", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequestBody Body;
        
        public GetPartnerIdByEmailRequest() {
        }
        
        public GetPartnerIdByEmailRequest(DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerIdByEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetPartnerIdByEmailRequestBody() {
        }
        
        public GetPartnerIdByEmailRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerIdByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerIdByEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponseBody Body;
        
        public GetPartnerIdByEmailResponse() {
        }
        
        public GetPartnerIdByEmailResponse(DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerIdByEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPartnerIdByEmailResult;
        
        public GetPartnerIdByEmailResponseBody() {
        }
        
        public GetPartnerIdByEmailResponseBody(int GetPartnerIdByEmailResult) {
            this.GetPartnerIdByEmailResult = GetPartnerIdByEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PartnerServicesSoapChannel : DebraEventManagement.PartnerServiceRef.PartnerServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartnerServicesSoapClient : System.ServiceModel.ClientBase<DebraEventManagement.PartnerServiceRef.PartnerServicesSoap>, DebraEventManagement.PartnerServiceRef.PartnerServicesSoap {
        
        public PartnerServicesSoapClient() {
        }
        
        public PartnerServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartnerServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.RegisterPartnerResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.RegisterPartner(DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartner(request);
        }
        
        public bool RegisterPartner(string partnerName, string email, string password) {
            DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest inValue = new DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.RegisterPartnerRequestBody();
            inValue.Body.partnerName = partnerName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            DebraEventManagement.PartnerServiceRef.RegisterPartnerResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).RegisterPartner(inValue);
            return retVal.Body.RegisterPartnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.RegisterPartnerResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.RegisterPartnerAsync(DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.RegisterPartnerResponse> RegisterPartnerAsync(string partnerName, string email, string password) {
            DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest inValue = new DebraEventManagement.PartnerServiceRef.RegisterPartnerRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.RegisterPartnerRequestBody();
            inValue.Body.partnerName = partnerName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).RegisterPartnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.LoginPartnerResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.LoginPartner(DebraEventManagement.PartnerServiceRef.LoginPartnerRequest request) {
            return base.Channel.LoginPartner(request);
        }
        
        public bool LoginPartner(string email, string password) {
            DebraEventManagement.PartnerServiceRef.LoginPartnerRequest inValue = new DebraEventManagement.PartnerServiceRef.LoginPartnerRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.LoginPartnerRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            DebraEventManagement.PartnerServiceRef.LoginPartnerResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).LoginPartner(inValue);
            return retVal.Body.LoginPartnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.LoginPartnerResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.LoginPartnerAsync(DebraEventManagement.PartnerServiceRef.LoginPartnerRequest request) {
            return base.Channel.LoginPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.LoginPartnerResponse> LoginPartnerAsync(string email, string password) {
            DebraEventManagement.PartnerServiceRef.LoginPartnerRequest inValue = new DebraEventManagement.PartnerServiceRef.LoginPartnerRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.LoginPartnerRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).LoginPartnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.CreateEventResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.CreateEvent(DebraEventManagement.PartnerServiceRef.CreateEventRequest request) {
            return base.Channel.CreateEvent(request);
        }
        
        public bool CreateEvent(string partnerEmail, string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            DebraEventManagement.PartnerServiceRef.CreateEventRequest inValue = new DebraEventManagement.PartnerServiceRef.CreateEventRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.CreateEventRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            inValue.Body.eventName = eventName;
            inValue.Body.eventDescription = eventDescription;
            inValue.Body.eventDate = eventDate;
            inValue.Body.eventTime = eventTime;
            inValue.Body.location = location;
            inValue.Body.link = link;
            DebraEventManagement.PartnerServiceRef.CreateEventResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).CreateEvent(inValue);
            return retVal.Body.CreateEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.CreateEventResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.CreateEventAsync(DebraEventManagement.PartnerServiceRef.CreateEventRequest request) {
            return base.Channel.CreateEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.CreateEventResponse> CreateEventAsync(string partnerEmail, string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            DebraEventManagement.PartnerServiceRef.CreateEventRequest inValue = new DebraEventManagement.PartnerServiceRef.CreateEventRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.CreateEventRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            inValue.Body.eventName = eventName;
            inValue.Body.eventDescription = eventDescription;
            inValue.Body.eventDate = eventDate;
            inValue.Body.eventTime = eventTime;
            inValue.Body.location = location;
            inValue.Body.link = link;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).CreateEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.SetTicketDetails(DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest request) {
            return base.Channel.SetTicketDetails(request);
        }
        
        public bool SetTicketDetails(int eventId, string ticketName, decimal price, int quantity) {
            DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest inValue = new DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequestBody();
            inValue.Body.eventId = eventId;
            inValue.Body.ticketName = ticketName;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).SetTicketDetails(inValue);
            return retVal.Body.SetTicketDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.SetTicketDetailsAsync(DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest request) {
            return base.Channel.SetTicketDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.SetTicketDetailsResponse> SetTicketDetailsAsync(int eventId, string ticketName, decimal price, int quantity) {
            DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest inValue = new DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.SetTicketDetailsRequestBody();
            inValue.Body.eventId = eventId;
            inValue.Body.ticketName = ticketName;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).SetTicketDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.CalculatePartnerEarnings(DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest request) {
            return base.Channel.CalculatePartnerEarnings(request);
        }
        
        public decimal CalculatePartnerEarnings(string partnerEmail) {
            DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest inValue = new DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).CalculatePartnerEarnings(inValue);
            return retVal.Body.CalculatePartnerEarningsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.CalculatePartnerEarningsAsync(DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest request) {
            return base.Channel.CalculatePartnerEarningsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsResponse> CalculatePartnerEarningsAsync(string partnerEmail) {
            DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest inValue = new DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.CalculatePartnerEarningsRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).CalculatePartnerEarningsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.GetEventsByPartnerId(DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest request) {
            return base.Channel.GetEventsByPartnerId(request);
        }
        
        public DebraEventManagement.PartnerServiceRef.Event[] GetEventsByPartnerId(int partnerId) {
            DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest inValue = new DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequestBody();
            inValue.Body.partnerId = partnerId;
            DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).GetEventsByPartnerId(inValue);
            return retVal.Body.GetEventsByPartnerIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.GetEventsByPartnerIdAsync(DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest request) {
            return base.Channel.GetEventsByPartnerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdResponse> GetEventsByPartnerIdAsync(int partnerId) {
            DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest inValue = new DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.GetEventsByPartnerIdRequestBody();
            inValue.Body.partnerId = partnerId;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).GetEventsByPartnerIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.GetPartnerTicketSales(DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest request) {
            return base.Channel.GetPartnerTicketSales(request);
        }
        
        public DebraEventManagement.PartnerServiceRef.EventSales[] GetPartnerTicketSales(int partnerId) {
            DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest inValue = new DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequestBody();
            inValue.Body.partnerId = partnerId;
            DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).GetPartnerTicketSales(inValue);
            return retVal.Body.GetPartnerTicketSalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.GetPartnerTicketSalesAsync(DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest request) {
            return base.Channel.GetPartnerTicketSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesResponse> GetPartnerTicketSalesAsync(int partnerId) {
            DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest inValue = new DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.GetPartnerTicketSalesRequestBody();
            inValue.Body.partnerId = partnerId;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).GetPartnerTicketSalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponse DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.GetPartnerIdByEmail(DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest request) {
            return base.Channel.GetPartnerIdByEmail(request);
        }
        
        public int GetPartnerIdByEmail(string email) {
            DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest inValue = new DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequestBody();
            inValue.Body.email = email;
            DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponse retVal = ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).GetPartnerIdByEmail(inValue);
            return retVal.Body.GetPartnerIdByEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponse> DebraEventManagement.PartnerServiceRef.PartnerServicesSoap.GetPartnerIdByEmailAsync(DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest request) {
            return base.Channel.GetPartnerIdByEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailResponse> GetPartnerIdByEmailAsync(string email) {
            DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest inValue = new DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequest();
            inValue.Body = new DebraEventManagement.PartnerServiceRef.GetPartnerIdByEmailRequestBody();
            inValue.Body.email = email;
            return ((DebraEventManagement.PartnerServiceRef.PartnerServicesSoap)(this)).GetPartnerIdByEmailAsync(inValue);
        }
    }
}
