//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebraEventManagement.AdminServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EventInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIDField;
        
        private int PartnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PartnerID {
            get {
                return this.PartnerIDField;
            }
            set {
                if ((this.PartnerIDField.Equals(value) != true)) {
                    this.PartnerIDField = value;
                    this.RaisePropertyChanged("PartnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EventDescription {
            get {
                return this.EventDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDescriptionField, value) != true)) {
                    this.EventDescriptionField = value;
                    this.RaisePropertyChanged("EventDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EventDate {
            get {
                return this.EventDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDateField, value) != true)) {
                    this.EventDateField = value;
                    this.RaisePropertyChanged("EventDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTimeField, value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partner", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Partner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PartnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PartnerID {
            get {
                return this.PartnerIDField;
            }
            set {
                if ((this.PartnerIDField.Equals(value) != true)) {
                    this.PartnerIDField = value;
                    this.RaisePropertyChanged("PartnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartnerName {
            get {
                return this.PartnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerNameField, value) != true)) {
                    this.PartnerNameField = value;
                    this.RaisePropertyChanged("PartnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketSaleInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TicketSaleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TicketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        private decimal PriceField;
        
        private int SoldField;
        
        private decimal TotalSaleField;
        
        private decimal AdminEarningsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TicketID {
            get {
                return this.TicketIDField;
            }
            set {
                if ((this.TicketIDField.Equals(value) != true)) {
                    this.TicketIDField = value;
                    this.RaisePropertyChanged("TicketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Sold {
            get {
                return this.SoldField;
            }
            set {
                if ((this.SoldField.Equals(value) != true)) {
                    this.SoldField = value;
                    this.RaisePropertyChanged("Sold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal TotalSale {
            get {
                return this.TotalSaleField;
            }
            set {
                if ((this.TotalSaleField.Equals(value) != true)) {
                    this.TotalSaleField = value;
                    this.RaisePropertyChanged("TotalSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal AdminEarnings {
            get {
                return this.AdminEarningsField;
            }
            set {
                if ((this.AdminEarningsField.Equals(value) != true)) {
                    this.AdminEarningsField = value;
                    this.RaisePropertyChanged("AdminEarnings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceRef.AdminServicesSoap")]
    public interface AdminServicesSoap {
        
        // CODEGEN: Generating message contract since element name GetAllEventsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEvents", ReplyAction="*")]
        DebraEventManagement.AdminServiceRef.GetAllEventsResponse GetAllEvents(DebraEventManagement.AdminServiceRef.GetAllEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetAllEventsResponse> GetAllEventsAsync(DebraEventManagement.AdminServiceRef.GetAllEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTicketsForEvent", ReplyAction="*")]
        bool DeleteTicketsForEvent(int eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTicketsForEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteTicketsForEventAsync(int eventID);
        
        // CODEGEN: Generating message contract since element name GetAllPartnersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPartners", ReplyAction="*")]
        DebraEventManagement.AdminServiceRef.GetAllPartnersResponse GetAllPartners(DebraEventManagement.AdminServiceRef.GetAllPartnersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPartners", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetAllPartnersResponse> GetAllPartnersAsync(DebraEventManagement.AdminServiceRef.GetAllPartnersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePartner", ReplyAction="*")]
        bool DeletePartner(int partnerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePartner", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeletePartnerAsync(int partnerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalSales", ReplyAction="*")]
        decimal GetTotalSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalSales", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> GetTotalSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalCommission", ReplyAction="*")]
        decimal GetTotalCommission();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalCommission", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> GetTotalCommissionAsync();
        
        // CODEGEN: Generating message contract since element name GetTicketSalesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketSales", ReplyAction="*")]
        DebraEventManagement.AdminServiceRef.GetTicketSalesResponse GetTicketSales(DebraEventManagement.AdminServiceRef.GetTicketSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketSales", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetTicketSalesResponse> GetTicketSalesAsync(DebraEventManagement.AdminServiceRef.GetTicketSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEvent", ReplyAction="*")]
        bool DeleteEvent(int eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEvents", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.GetAllEventsRequestBody Body;
        
        public GetAllEventsRequest() {
        }
        
        public GetAllEventsRequest(DebraEventManagement.AdminServiceRef.GetAllEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEventsRequestBody {
        
        public GetAllEventsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEventsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.GetAllEventsResponseBody Body;
        
        public GetAllEventsResponse() {
        }
        
        public GetAllEventsResponse(DebraEventManagement.AdminServiceRef.GetAllEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagement.AdminServiceRef.EventInfo[] GetAllEventsResult;
        
        public GetAllEventsResponseBody() {
        }
        
        public GetAllEventsResponseBody(DebraEventManagement.AdminServiceRef.EventInfo[] GetAllEventsResult) {
            this.GetAllEventsResult = GetAllEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPartnersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPartners", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.GetAllPartnersRequestBody Body;
        
        public GetAllPartnersRequest() {
        }
        
        public GetAllPartnersRequest(DebraEventManagement.AdminServiceRef.GetAllPartnersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPartnersRequestBody {
        
        public GetAllPartnersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPartnersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPartnersResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.GetAllPartnersResponseBody Body;
        
        public GetAllPartnersResponse() {
        }
        
        public GetAllPartnersResponse(DebraEventManagement.AdminServiceRef.GetAllPartnersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPartnersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagement.AdminServiceRef.Partner[] GetAllPartnersResult;
        
        public GetAllPartnersResponseBody() {
        }
        
        public GetAllPartnersResponseBody(DebraEventManagement.AdminServiceRef.Partner[] GetAllPartnersResult) {
            this.GetAllPartnersResult = GetAllPartnersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketSalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketSales", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.GetTicketSalesRequestBody Body;
        
        public GetTicketSalesRequest() {
        }
        
        public GetTicketSalesRequest(DebraEventManagement.AdminServiceRef.GetTicketSalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTicketSalesRequestBody {
        
        public GetTicketSalesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketSalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketSalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.GetTicketSalesResponseBody Body;
        
        public GetTicketSalesResponse() {
        }
        
        public GetTicketSalesResponse(DebraEventManagement.AdminServiceRef.GetTicketSalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketSalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagement.AdminServiceRef.TicketSaleInfo[] GetTicketSalesResult;
        
        public GetTicketSalesResponseBody() {
        }
        
        public GetTicketSalesResponseBody(DebraEventManagement.AdminServiceRef.TicketSaleInfo[] GetTicketSalesResult) {
            this.GetTicketSalesResult = GetTicketSalesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServicesSoapChannel : DebraEventManagement.AdminServiceRef.AdminServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServicesSoapClient : System.ServiceModel.ClientBase<DebraEventManagement.AdminServiceRef.AdminServicesSoap>, DebraEventManagement.AdminServiceRef.AdminServicesSoap {
        
        public AdminServicesSoapClient() {
        }
        
        public AdminServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.AdminServiceRef.GetAllEventsResponse DebraEventManagement.AdminServiceRef.AdminServicesSoap.GetAllEvents(DebraEventManagement.AdminServiceRef.GetAllEventsRequest request) {
            return base.Channel.GetAllEvents(request);
        }
        
        public DebraEventManagement.AdminServiceRef.EventInfo[] GetAllEvents() {
            DebraEventManagement.AdminServiceRef.GetAllEventsRequest inValue = new DebraEventManagement.AdminServiceRef.GetAllEventsRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.GetAllEventsRequestBody();
            DebraEventManagement.AdminServiceRef.GetAllEventsResponse retVal = ((DebraEventManagement.AdminServiceRef.AdminServicesSoap)(this)).GetAllEvents(inValue);
            return retVal.Body.GetAllEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetAllEventsResponse> DebraEventManagement.AdminServiceRef.AdminServicesSoap.GetAllEventsAsync(DebraEventManagement.AdminServiceRef.GetAllEventsRequest request) {
            return base.Channel.GetAllEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetAllEventsResponse> GetAllEventsAsync() {
            DebraEventManagement.AdminServiceRef.GetAllEventsRequest inValue = new DebraEventManagement.AdminServiceRef.GetAllEventsRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.GetAllEventsRequestBody();
            return ((DebraEventManagement.AdminServiceRef.AdminServicesSoap)(this)).GetAllEventsAsync(inValue);
        }
        
        public bool DeleteTicketsForEvent(int eventID) {
            return base.Channel.DeleteTicketsForEvent(eventID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTicketsForEventAsync(int eventID) {
            return base.Channel.DeleteTicketsForEventAsync(eventID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.AdminServiceRef.GetAllPartnersResponse DebraEventManagement.AdminServiceRef.AdminServicesSoap.GetAllPartners(DebraEventManagement.AdminServiceRef.GetAllPartnersRequest request) {
            return base.Channel.GetAllPartners(request);
        }
        
        public DebraEventManagement.AdminServiceRef.Partner[] GetAllPartners() {
            DebraEventManagement.AdminServiceRef.GetAllPartnersRequest inValue = new DebraEventManagement.AdminServiceRef.GetAllPartnersRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.GetAllPartnersRequestBody();
            DebraEventManagement.AdminServiceRef.GetAllPartnersResponse retVal = ((DebraEventManagement.AdminServiceRef.AdminServicesSoap)(this)).GetAllPartners(inValue);
            return retVal.Body.GetAllPartnersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetAllPartnersResponse> DebraEventManagement.AdminServiceRef.AdminServicesSoap.GetAllPartnersAsync(DebraEventManagement.AdminServiceRef.GetAllPartnersRequest request) {
            return base.Channel.GetAllPartnersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetAllPartnersResponse> GetAllPartnersAsync() {
            DebraEventManagement.AdminServiceRef.GetAllPartnersRequest inValue = new DebraEventManagement.AdminServiceRef.GetAllPartnersRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.GetAllPartnersRequestBody();
            return ((DebraEventManagement.AdminServiceRef.AdminServicesSoap)(this)).GetAllPartnersAsync(inValue);
        }
        
        public bool DeletePartner(int partnerID) {
            return base.Channel.DeletePartner(partnerID);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePartnerAsync(int partnerID) {
            return base.Channel.DeletePartnerAsync(partnerID);
        }
        
        public decimal GetTotalSales() {
            return base.Channel.GetTotalSales();
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalSalesAsync() {
            return base.Channel.GetTotalSalesAsync();
        }
        
        public decimal GetTotalCommission() {
            return base.Channel.GetTotalCommission();
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalCommissionAsync() {
            return base.Channel.GetTotalCommissionAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.AdminServiceRef.GetTicketSalesResponse DebraEventManagement.AdminServiceRef.AdminServicesSoap.GetTicketSales(DebraEventManagement.AdminServiceRef.GetTicketSalesRequest request) {
            return base.Channel.GetTicketSales(request);
        }
        
        public DebraEventManagement.AdminServiceRef.TicketSaleInfo[] GetTicketSales() {
            DebraEventManagement.AdminServiceRef.GetTicketSalesRequest inValue = new DebraEventManagement.AdminServiceRef.GetTicketSalesRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.GetTicketSalesRequestBody();
            DebraEventManagement.AdminServiceRef.GetTicketSalesResponse retVal = ((DebraEventManagement.AdminServiceRef.AdminServicesSoap)(this)).GetTicketSales(inValue);
            return retVal.Body.GetTicketSalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetTicketSalesResponse> DebraEventManagement.AdminServiceRef.AdminServicesSoap.GetTicketSalesAsync(DebraEventManagement.AdminServiceRef.GetTicketSalesRequest request) {
            return base.Channel.GetTicketSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.GetTicketSalesResponse> GetTicketSalesAsync() {
            DebraEventManagement.AdminServiceRef.GetTicketSalesRequest inValue = new DebraEventManagement.AdminServiceRef.GetTicketSalesRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.GetTicketSalesRequestBody();
            return ((DebraEventManagement.AdminServiceRef.AdminServicesSoap)(this)).GetTicketSalesAsync(inValue);
        }
        
        public bool DeleteEvent(int eventID) {
            return base.Channel.DeleteEvent(eventID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEventAsync(int eventID) {
            return base.Channel.DeleteEventAsync(eventID);
        }
    }
}
