//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebraEventManagementDesktop.PartnerServiceRefDesktop {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventSales", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EventSales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        private int TicketsSoldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TicketsSold {
            get {
                return this.TicketsSoldField;
            }
            set {
                if ((this.TicketsSoldField.Equals(value) != true)) {
                    this.TicketsSoldField = value;
                    this.RaisePropertyChanged("TicketsSold");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartnerServiceRefDesktop.PartnerServicesSoap")]
    public interface PartnerServicesSoap {
        
        // CODEGEN: Generating message contract since element name partnerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponse RegisterPartner(DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponse> RegisterPartnerAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginPartner", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponse LoginPartner(DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponse> LoginPartnerAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest request);
        
        // CODEGEN: Generating message contract since element name partnerEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEvent", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponse CreateEvent(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponse> CreateEventAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest request);
        
        // CODEGEN: Generating message contract since element name eventName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEventAdmin", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponse CreateEventAdmin(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEventAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponse> CreateEventAdminAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest request);
        
        // CODEGEN: Generating message contract since element name ticketName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTicketDetails", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponse SetTicketDetails(DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTicketDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponse> SetTicketDetailsAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name partnerEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatePartnerEarnings", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponse CalculatePartnerEarnings(DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatePartnerEarnings", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponse> CalculatePartnerEarningsAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventsByPartnerIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsByPartnerId", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponse GetEventsByPartnerId(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsByPartnerId", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponse> GetEventsByPartnerIdAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetPartnerTicketSalesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerTicketSales", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponse GetPartnerTicketSales(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerTicketSales", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponse> GetPartnerTicketSalesAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerIdByEmail", ReplyAction="*")]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponse GetPartnerIdByEmail(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartnerIdByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponse> GetPartnerIdByEmailAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartner", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequestBody Body;
        
        public RegisterPartnerRequest() {
        }
        
        public RegisterPartnerRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public RegisterPartnerRequestBody() {
        }
        
        public RegisterPartnerRequestBody(string partnerName, string email, string password) {
            this.partnerName = partnerName;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponseBody Body;
        
        public RegisterPartnerResponse() {
        }
        
        public RegisterPartnerResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterPartnerResult;
        
        public RegisterPartnerResponseBody() {
        }
        
        public RegisterPartnerResponseBody(bool RegisterPartnerResult) {
            this.RegisterPartnerResult = RegisterPartnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginPartnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginPartner", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequestBody Body;
        
        public LoginPartnerRequest() {
        }
        
        public LoginPartnerRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginPartnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginPartnerRequestBody() {
        }
        
        public LoginPartnerRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginPartnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginPartnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponseBody Body;
        
        public LoginPartnerResponse() {
        }
        
        public LoginPartnerResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginPartnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginPartnerResult;
        
        public LoginPartnerResponseBody() {
        }
        
        public LoginPartnerResponseBody(bool LoginPartnerResult) {
            this.LoginPartnerResult = LoginPartnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEvent", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequestBody Body;
        
        public CreateEventRequest() {
        }
        
        public CreateEventRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string eventName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eventDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string eventDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eventTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string link;
        
        public CreateEventRequestBody() {
        }
        
        public CreateEventRequestBody(string partnerEmail, string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            this.partnerEmail = partnerEmail;
            this.eventName = eventName;
            this.eventDescription = eventDescription;
            this.eventDate = eventDate;
            this.eventTime = eventTime;
            this.location = location;
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEventResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponseBody Body;
        
        public CreateEventResponse() {
        }
        
        public CreateEventResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEventResult;
        
        public CreateEventResponseBody() {
        }
        
        public CreateEventResponseBody(bool CreateEventResult) {
            this.CreateEventResult = CreateEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEventAdmin", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequestBody Body;
        
        public CreateEventAdminRequest() {
        }
        
        public CreateEventAdminRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEventAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eventName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string eventDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eventDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string eventTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string link;
        
        public CreateEventAdminRequestBody() {
        }
        
        public CreateEventAdminRequestBody(string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            this.eventName = eventName;
            this.eventDescription = eventDescription;
            this.eventDate = eventDate;
            this.eventTime = eventTime;
            this.location = location;
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEventAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEventAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponseBody Body;
        
        public CreateEventAdminResponse() {
        }
        
        public CreateEventAdminResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEventAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEventAdminResult;
        
        public CreateEventAdminResponseBody() {
        }
        
        public CreateEventAdminResponseBody(bool CreateEventAdminResult) {
            this.CreateEventAdminResult = CreateEventAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTicketDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTicketDetails", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequestBody Body;
        
        public SetTicketDetailsRequest() {
        }
        
        public SetTicketDetailsRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetTicketDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int eventId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ticketName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        public SetTicketDetailsRequestBody() {
        }
        
        public SetTicketDetailsRequestBody(int eventId, string ticketName, decimal price, int quantity) {
            this.eventId = eventId;
            this.ticketName = ticketName;
            this.price = price;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTicketDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTicketDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponseBody Body;
        
        public SetTicketDetailsResponse() {
        }
        
        public SetTicketDetailsResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetTicketDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetTicketDetailsResult;
        
        public SetTicketDetailsResponseBody() {
        }
        
        public SetTicketDetailsResponseBody(bool SetTicketDetailsResult) {
            this.SetTicketDetailsResult = SetTicketDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePartnerEarningsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePartnerEarnings", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequestBody Body;
        
        public CalculatePartnerEarningsRequest() {
        }
        
        public CalculatePartnerEarningsRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculatePartnerEarningsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerEmail;
        
        public CalculatePartnerEarningsRequestBody() {
        }
        
        public CalculatePartnerEarningsRequestBody(string partnerEmail) {
            this.partnerEmail = partnerEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePartnerEarningsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePartnerEarningsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponseBody Body;
        
        public CalculatePartnerEarningsResponse() {
        }
        
        public CalculatePartnerEarningsResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculatePartnerEarningsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal CalculatePartnerEarningsResult;
        
        public CalculatePartnerEarningsResponseBody() {
        }
        
        public CalculatePartnerEarningsResponseBody(decimal CalculatePartnerEarningsResult) {
            this.CalculatePartnerEarningsResult = CalculatePartnerEarningsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsByPartnerIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsByPartnerId", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequestBody Body;
        
        public GetEventsByPartnerIdRequest() {
        }
        
        public GetEventsByPartnerIdRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventsByPartnerIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int partnerId;
        
        public GetEventsByPartnerIdRequestBody() {
        }
        
        public GetEventsByPartnerIdRequestBody(int partnerId) {
            this.partnerId = partnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsByPartnerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsByPartnerIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponseBody Body;
        
        public GetEventsByPartnerIdResponse() {
        }
        
        public GetEventsByPartnerIdResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventsByPartnerIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.Event[] GetEventsByPartnerIdResult;
        
        public GetEventsByPartnerIdResponseBody() {
        }
        
        public GetEventsByPartnerIdResponseBody(DebraEventManagementDesktop.PartnerServiceRefDesktop.Event[] GetEventsByPartnerIdResult) {
            this.GetEventsByPartnerIdResult = GetEventsByPartnerIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerTicketSalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerTicketSales", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequestBody Body;
        
        public GetPartnerTicketSalesRequest() {
        }
        
        public GetPartnerTicketSalesRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerTicketSalesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int partnerId;
        
        public GetPartnerTicketSalesRequestBody() {
        }
        
        public GetPartnerTicketSalesRequestBody(int partnerId) {
            this.partnerId = partnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerTicketSalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerTicketSalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponseBody Body;
        
        public GetPartnerTicketSalesResponse() {
        }
        
        public GetPartnerTicketSalesResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerTicketSalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.EventSales[] GetPartnerTicketSalesResult;
        
        public GetPartnerTicketSalesResponseBody() {
        }
        
        public GetPartnerTicketSalesResponseBody(DebraEventManagementDesktop.PartnerServiceRefDesktop.EventSales[] GetPartnerTicketSalesResult) {
            this.GetPartnerTicketSalesResult = GetPartnerTicketSalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerIdByEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerIdByEmail", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequestBody Body;
        
        public GetPartnerIdByEmailRequest() {
        }
        
        public GetPartnerIdByEmailRequest(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerIdByEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetPartnerIdByEmailRequestBody() {
        }
        
        public GetPartnerIdByEmailRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerIdByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerIdByEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponseBody Body;
        
        public GetPartnerIdByEmailResponse() {
        }
        
        public GetPartnerIdByEmailResponse(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartnerIdByEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPartnerIdByEmailResult;
        
        public GetPartnerIdByEmailResponseBody() {
        }
        
        public GetPartnerIdByEmailResponseBody(int GetPartnerIdByEmailResult) {
            this.GetPartnerIdByEmailResult = GetPartnerIdByEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PartnerServicesSoapChannel : DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartnerServicesSoapClient : System.ServiceModel.ClientBase<DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap>, DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap {
        
        public PartnerServicesSoapClient() {
        }
        
        public PartnerServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartnerServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.RegisterPartner(DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartner(request);
        }
        
        public bool RegisterPartner(string partnerName, string email, string password) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequestBody();
            inValue.Body.partnerName = partnerName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).RegisterPartner(inValue);
            return retVal.Body.RegisterPartnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.RegisterPartnerAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerResponse> RegisterPartnerAsync(string partnerName, string email, string password) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.RegisterPartnerRequestBody();
            inValue.Body.partnerName = partnerName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).RegisterPartnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.LoginPartner(DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest request) {
            return base.Channel.LoginPartner(request);
        }
        
        public bool LoginPartner(string email, string password) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).LoginPartner(inValue);
            return retVal.Body.LoginPartnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.LoginPartnerAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest request) {
            return base.Channel.LoginPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerResponse> LoginPartnerAsync(string email, string password) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.LoginPartnerRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).LoginPartnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.CreateEvent(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest request) {
            return base.Channel.CreateEvent(request);
        }
        
        public bool CreateEvent(string partnerEmail, string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            inValue.Body.eventName = eventName;
            inValue.Body.eventDescription = eventDescription;
            inValue.Body.eventDate = eventDate;
            inValue.Body.eventTime = eventTime;
            inValue.Body.location = location;
            inValue.Body.link = link;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).CreateEvent(inValue);
            return retVal.Body.CreateEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.CreateEventAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest request) {
            return base.Channel.CreateEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventResponse> CreateEventAsync(string partnerEmail, string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            inValue.Body.eventName = eventName;
            inValue.Body.eventDescription = eventDescription;
            inValue.Body.eventDate = eventDate;
            inValue.Body.eventTime = eventTime;
            inValue.Body.location = location;
            inValue.Body.link = link;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).CreateEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.CreateEventAdmin(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest request) {
            return base.Channel.CreateEventAdmin(request);
        }
        
        public bool CreateEventAdmin(string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequestBody();
            inValue.Body.eventName = eventName;
            inValue.Body.eventDescription = eventDescription;
            inValue.Body.eventDate = eventDate;
            inValue.Body.eventTime = eventTime;
            inValue.Body.location = location;
            inValue.Body.link = link;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).CreateEventAdmin(inValue);
            return retVal.Body.CreateEventAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.CreateEventAdminAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest request) {
            return base.Channel.CreateEventAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminResponse> CreateEventAdminAsync(string eventName, string eventDescription, string eventDate, string eventTime, string location, string link) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CreateEventAdminRequestBody();
            inValue.Body.eventName = eventName;
            inValue.Body.eventDescription = eventDescription;
            inValue.Body.eventDate = eventDate;
            inValue.Body.eventTime = eventTime;
            inValue.Body.location = location;
            inValue.Body.link = link;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).CreateEventAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.SetTicketDetails(DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest request) {
            return base.Channel.SetTicketDetails(request);
        }
        
        public bool SetTicketDetails(int eventId, string ticketName, decimal price, int quantity) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequestBody();
            inValue.Body.eventId = eventId;
            inValue.Body.ticketName = ticketName;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).SetTicketDetails(inValue);
            return retVal.Body.SetTicketDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.SetTicketDetailsAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest request) {
            return base.Channel.SetTicketDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsResponse> SetTicketDetailsAsync(int eventId, string ticketName, decimal price, int quantity) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.SetTicketDetailsRequestBody();
            inValue.Body.eventId = eventId;
            inValue.Body.ticketName = ticketName;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).SetTicketDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.CalculatePartnerEarnings(DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest request) {
            return base.Channel.CalculatePartnerEarnings(request);
        }
        
        public decimal CalculatePartnerEarnings(string partnerEmail) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).CalculatePartnerEarnings(inValue);
            return retVal.Body.CalculatePartnerEarningsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.CalculatePartnerEarningsAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest request) {
            return base.Channel.CalculatePartnerEarningsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsResponse> CalculatePartnerEarningsAsync(string partnerEmail) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.CalculatePartnerEarningsRequestBody();
            inValue.Body.partnerEmail = partnerEmail;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).CalculatePartnerEarningsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.GetEventsByPartnerId(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest request) {
            return base.Channel.GetEventsByPartnerId(request);
        }
        
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.Event[] GetEventsByPartnerId(int partnerId) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequestBody();
            inValue.Body.partnerId = partnerId;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).GetEventsByPartnerId(inValue);
            return retVal.Body.GetEventsByPartnerIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.GetEventsByPartnerIdAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest request) {
            return base.Channel.GetEventsByPartnerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdResponse> GetEventsByPartnerIdAsync(int partnerId) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetEventsByPartnerIdRequestBody();
            inValue.Body.partnerId = partnerId;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).GetEventsByPartnerIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.GetPartnerTicketSales(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest request) {
            return base.Channel.GetPartnerTicketSales(request);
        }
        
        public DebraEventManagementDesktop.PartnerServiceRefDesktop.EventSales[] GetPartnerTicketSales(int partnerId) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequestBody();
            inValue.Body.partnerId = partnerId;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).GetPartnerTicketSales(inValue);
            return retVal.Body.GetPartnerTicketSalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.GetPartnerTicketSalesAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest request) {
            return base.Channel.GetPartnerTicketSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesResponse> GetPartnerTicketSalesAsync(int partnerId) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerTicketSalesRequestBody();
            inValue.Body.partnerId = partnerId;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).GetPartnerTicketSalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponse DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.GetPartnerIdByEmail(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest request) {
            return base.Channel.GetPartnerIdByEmail(request);
        }
        
        public int GetPartnerIdByEmail(string email) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequestBody();
            inValue.Body.email = email;
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponse retVal = ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).GetPartnerIdByEmail(inValue);
            return retVal.Body.GetPartnerIdByEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponse> DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap.GetPartnerIdByEmailAsync(DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest request) {
            return base.Channel.GetPartnerIdByEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailResponse> GetPartnerIdByEmailAsync(string email) {
            DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest inValue = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequest();
            inValue.Body = new DebraEventManagementDesktop.PartnerServiceRefDesktop.GetPartnerIdByEmailRequestBody();
            inValue.Body.email = email;
            return ((DebraEventManagementDesktop.PartnerServiceRefDesktop.PartnerServicesSoap)(this)).GetPartnerIdByEmailAsync(inValue);
        }
    }
}
